### ISSUE TITLE
Remove old code

### ISSUE THREAD

**Issue by BenediktBurger** [pymeasure/pyleco#42]
- [x] `Coordinator.handle_commands`: do not interpret the bytes message, but the returned object #50
- [x] `Communicator.ask_raw`: do not search for "jsonrpc" in message bytes. #48
- [x] `ExtendedMessageHandler`: drop support for legacy messages, add a warning previous, though. #48

**Comment by BenediktBurger** [comment]
Done
